# Site settings
title: Paul S.I Basondole
#twitter_username:
name: Paul S.I Basondole

# Build settings
markdown: kramdown

#Navbar links
primarylinks:
 - title: GitHub
   url: https://github.com/basondole
 - title: LinkedIn
   url: https://www.linkedin.com/in/paul-i-2b3013108

skills:
 - IP Networks
 - MPLS
 - Ethernet Switching
 - Ansible
 - Python
 - Linux
 - Network Design
 - Network Automation
 - Collaboration


#Blogfeed 
blogfeed: 
  <a href="https://github.com/basondole/blog/blob/master/Understanding%20GPON.md#gpon-overview">Understanding GPON</a><br>
  <a href="https://github.com/basondole/blog/blob/master/Understanding%20Label%20Distribution.md#ldp--mpls-forwarding">Label distribution in MPLS</a><br>
  <a href="https://github.com/basondole/blog/blob/master/Understanding%20MPLS%20L2VPNs.md#mpls-l2vpns">MPLS Layer 2 VPNs Explained</a><br>
  <a href="https://github.com/basondole/blog/blob/master/Understanding%20Route-distinguishers%20and%20Route-targets.md#route-distinguisher">Route-distinguisher vs route-target</a>
  
# Network topic
networktopics:
  <a href="https://github.com/basondole/bgp/blob/master/BGP%20Conditional%20Advertisement.md#bgp-conditional-advertisement">BGP Conditional Advertisement</a><br>
  <a href="https://github.com/basondole/netmanagement/blob/master/Cisco%20Control%20Plane%20Policing.md#control-plane-policing">Cisco Control Plane Policing</a><br>
  <a href="https://github.com/basondole/netmanagement/blob/master/Huawei%20OLT%20CLI.md#essential-huawei-olt-cli-commands">Huawei OLT CLI</a><br>  
  <a href="https://github.com/basondole/netmanagement/blob/master/NAT%20with%20RouterOS.md#nat-rules-for-mikrotik-routers">Guide to NAT with MikroTik</a> 
  
collaboration:
  <a href="https://github.com/basondole/collaboration/blob/master/Setting%20up%20Cisco%20Call%20Manager.md#setting-up-cisco-call-manager-express">Setting up Call Manager</a><br>

#mytools:
#  <a href="http://41.221.32.208/smokeping/">Smokeping server</a><br>

opencode:
  <a href="https://github.com/basondole/hocid#readme">Huawei OLT Config diff</a><br>

coursera:
   #profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
   courses:
    - title: Tutorials
      link: https://github.com/basondole/tutorials#to-view-contents-choose-the-topic-of-interest-from-above-list
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
      date: Instruction on deployment of various network tools for management, monitoring and testing
    - title: Designs
      link: https://github.com/basondole/mpls#introduction
      optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
      date: Highlight of some of the designs in IP/MPLS

#My interesting Github repos
github:
 - basondole/open
 - basondole/topmapper


intro: |
   <p style = "font-family:georgia,garamond,serif;font-size:18px;font-style:italic;">
   <pre>READ CODE,<br/>
   &Tab;UTILIZE CODE,<br/>
   &Tab; &Tab; CREATE CODE YOURSELF and become a maestro
   </p></pre><br/>
   Scuba dive through articles and demonstration of various technologies related 
   to IP and MPLS networks and network programability in this poor man's blogsite &#x1F60F;<br/><br/>


additionalinfo: |
   I am scientist who loves working with technology and study about science &#x1F9D0;
   I have primarily worked on service provider core networks, internet exchanges and peering
   thereon developing and building complex network designs for enterprise customers. <br/><br/>  
   Currently im cheating with virtualization and network programability stuff development of 
   applications to support easy deloyment and management of services in service providers environments
   as technologies and the industry evolve and shift towards the software defined realm. <br/><br/>
   
   Call me when you want to discuss about ancient mythology &#128030; 
   the universe &#127756; and behavioural sciences &#129299; <br/><br/>
   
   Certifications &#128218; CCNPx1 JNCIPx2 <br/><br/>

theme: jekyll-theme-minimal
